import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import { FiChevronDown, FiPhone, FiMail, FiShare2 } from "react-icons/fi";
import styles from "../styles/Home.module.css";
import { FaInstagram } from "react-icons/fa";
import {
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  Button,
  MenuItemOption,
  MenuGroup,
  Text,
  MenuOptionGroup,
  MenuDivider,
  Box,
} from "@chakra-ui/react";
import laMarDeRojo from "../public/9M6A3040.jpeg";
import MusicPlayer from "./MusicPlayer";
import { LocalMusicPlayer } from "./LocalMusicPlayer";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <Box px={8}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <Menu
          closeOnBlur
          closeOnSelect
          isOpen={isOpen}
          onOpen={() => setIsOpen(true)}
          onClose={() => setIsOpen(false)}
        >
          <MenuButton
            onMouseEnter={() => setIsOpen(true)}
            as={Text}
            _hover={{ fontWeight: "bold" }}
            fontSize={"2xl"}
            m={0}
          >
            gotoxyc
          </MenuButton>

          <MenuList>
            <MenuItem>gallery</MenuItem>
            <MenuItem>tattoo art</MenuItem>
            <MenuItem>pottery</MenuItem>
            <MenuItem>performance</MenuItem>
            <MenuItem>paintings</MenuItem>
            <MenuItem>clothing</MenuItem>
            <MenuDivider />
            <MenuGroup title="Contact">
              <MenuItem display={"flex"} gap={12}>
                <FiPhone />
                <FaInstagram />
                <FiMail />
                <FiShare2> </FiShare2>
              </MenuItem>
            </MenuGroup>
          </MenuList>
        </Menu>

        <Box display={"flex"} gap={6}>
          <a> gallery</a>
          <a> contact</a>
          <a> cart</a>
        </Box>
      </div>

      <div
        style={{
          width: "300px",
        }}
      >
        <Image
          src={laMarDeRojo}
          alt="Una muchacha vestida de rojo"
          placeholder="blur"
          sizes="10vw"
        />

        <LocalMusicPlayer />
      </div>
    </Box>
  );
}
